# Basic information
title: Bo Fu
position: Ph.D. Student
affiliation: Shanghai Jiao Tong University
affiliation_link: https://en.sjtu.edu.cn/
email: fubo0970@sjtu.edu.cn

# Search engine optimization
keywords: Bo Fu, Computer Science, Shanghai Jiao Tong University
description: Academic homepage of Bo Fu, a Ph.D. student in Computer Science at Shanghai Jiao Tong University.
canonical: https://mosms.github.io/
url: https://mosms.github.io
baseurl: ""

# Links
cv_link: assets/files/CV.pdf
github_link: https://github.com/Mosms

# Images
avatar: assets/images/selfdraw.jpg
favicon: assets/images/mologo.png

# Theme options
enable_footnote: true

# Jekyll settings
markdown: kramdown
permalink: /:title/
plugins: []

exclude:
  - Dockerfile
  - compose.yaml
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
